[package]
name = "rattan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.68"
ctrlc = "3.2.5"
etherparse = "0.13.0"
futures = "0.3.26"
libc = "0.2.141"
nix = "0.26.2"
rand = "0.8.5"
regex = "1.7.3"
rtnetlink = "0.12.0"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "time", "net", "sync", "signal", "tokio-macros", "macros"] }
tokio-util = "0.7.7"

[dev-dependencies]
ctrlc = "3.2.5"
netns-rs = "0.1.0"
