[package]
name = "rattan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
futures = "0.3.26"
libc = "0.2.141"
nix = "0.26.2"
rtnetlink = "0.12.0"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["rt-multi-thread"] }

[dev-dependencies]
netns-rs = "0.1.0"
